import os
from PIL import Image

def fix_transparency(img_path):
    print(f"Processing {img_path}...")
    img = Image.open(img_path).convert("RGBA")
    datas = img.getdata()

    new_data = []
    for item in datas:
        # 1. Remove Checkerboard (approximate gray/white)
        # Very light gray (200+) or white (255)
        # Checking for common checkerboard patterns generated by AI
        if item[0] > 180 and item[1] > 180 and item[2] > 180:
             # Make it transparent
             new_data.append((255, 255, 255, 0))
        # 2. Remove Pure Black Background
        elif item[0] < 10 and item[1] < 10 and item[2] < 10:
             new_data.append((0, 0, 0, 0))
        else:
            new_data.append(item)

    img.putdata(new_data)
    img.save(img_path, "PNG")
    print(f"Fixed {img_path}")

menu_dir = "/home/michael/proj/dcgame/images/menu"
for filename in os.listdir(menu_dir):
    if filename.endswith(".png"):
        fix_transparency(os.path.join(menu_dir, filename))
